/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 package com.mycompany.d2;
 

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
 
import java.text.SimpleDateFormat;
import java.util.Date;
//import javafx.scene.control.TableColumn;
import javax.swing.table.DefaultTableModel;
import java.text.*;
 
import java.util.Calendar;
import java.util.Locale;
//import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
 
import java.util.Observable;
import java.util.Observer;
 

/**
 *
 * @author sarion
 */
public class View extends javax.swing.JFrame  implements Observer {

    /**
     * Creates new form MainJFrame
     */

    DateFormat dateFormat = new SimpleDateFormat("EEEE MMM dd YYYY",Locale.US);
    Date date = new Date();
    Calendar cal = Calendar.getInstance();
    DefaultTableModel model;
    
    DateFormat dateFormat2 = new SimpleDateFormat("hh:mm a");
 
   
    
    public View() {
          initComponents(); 
        
          model = (DefaultTableModel) jTable_FoodList.getModel();
          
          //defaut setting
          jRadioButton_Eaten.setSelected(true);
          type_select();
          jTextField_Calendar.setText(" "+dateFormat.format(date));
          jTextField_Time.setText(" "+dateFormat2.format(date));
          jRadioButton_Fall.setSelected(true);
                
          /* javax.swing.table.TableColumn sexColumn =  jTable_FoodList.getColumnModel().getColumn(1);
           sexColumn.setCellEditor(new DefaultCellEditor(new Type())); // tablelist add downlist */           
         
    }

     // type defaut: in dinning
     private void type_select(){
    
         if (jComboBox_Type.getSelectedItem().equals("In Dinning")) {

            jTextField_Name.setEditable(true);
            jTextField_Name.setText("");
            jTextField_ServingSize.setEditable(true);
            jTextField_ServingSize.setText("");
            jTextField_Retailer.setText("N.A");
            jTextField_Retailer.setEditable(false);
            jTextField_Meal.setText("N.A");
            jTextField_Meal.setEditable(false);
            jTextField_Group.setText("N.A");
            jTextField_Group.setEditable(false);

        }
        else if (jComboBox_Type.getSelectedItem().equals("Out Dinning")){

            jTextField_Name.setText("N.A");
            jTextField_Name.setEditable(false);
            jTextField_ServingSize.setText("N.A");
            jTextField_ServingSize.setEditable(false);
            jTextField_Retailer.setEditable(true);
            jTextField_Retailer.setText("");
            jTextField_Meal.setEditable(true);
            jTextField_Meal.setText("");
            jTextField_Group.setEditable(true);
            jTextField_Group.setText("");
        }


     }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel_FoodItem = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_FoodList = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton_Delete = new javax.swing.JButton();
        JButton_Add = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTextField_Retailer = new javax.swing.JTextField();
        jTextField_Meal = new javax.swing.JTextField();
        jTextField_Group = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_Type = new javax.swing.JComboBox<>();
        jRadioButton_Eaten = new javax.swing.JRadioButton();
        jTextField_Calendar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Time = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Calories = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Fat = new javax.swing.JTextField();
        jTextField_Portein = new javax.swing.JTextField();
        jTextField_Cholesterol = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_Sodium = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField_Carbohydrate = new javax.swing.JTextField();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField_ServingSize = new javax.swing.JTextField();
        jComboBox_Unit = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jRadioButton_Fall = new javax.swing.JRadioButton();
        jRadioButton_Featen = new javax.swing.JRadioButton();
        jRadioButton_Funeaten = new javax.swing.JRadioButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel_FoodItem.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_FoodItem.setText("Food Item List");

        jTable_FoodList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Eaten", "Type", "Calendar", "Time", "Name", "Serving Size", "Unit", "Retailer", "Meal", "Group", "Calories", "Fat", "Carbohydrate", "Protein", "Cholesterol", "Sodium"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_FoodList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable_FoodListAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable_FoodList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_FoodListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_FoodList);
        if (jTable_FoodList.getColumnModel().getColumnCount() > 0) {
            jTable_FoodList.getColumnModel().getColumn(0).setMinWidth(30);
            jTable_FoodList.getColumnModel().getColumn(1).setMinWidth(80);
            jTable_FoodList.getColumnModel().getColumn(2).setMinWidth(160);
            jTable_FoodList.getColumnModel().getColumn(3).setMinWidth(80);
            jTable_FoodList.getColumnModel().getColumn(4).setMinWidth(100);
            jTable_FoodList.getColumnModel().getColumn(5).setMinWidth(100);
            jTable_FoodList.getColumnModel().getColumn(6).setMinWidth(20);
            jTable_FoodList.getColumnModel().getColumn(7).setMinWidth(100);
            jTable_FoodList.getColumnModel().getColumn(8).setMinWidth(100);
            jTable_FoodList.getColumnModel().getColumn(9).setMinWidth(80);
            jTable_FoodList.getColumnModel().getColumn(10).setMinWidth(60);
            jTable_FoodList.getColumnModel().getColumn(11).setMinWidth(40);
            jTable_FoodList.getColumnModel().getColumn(12).setMinWidth(40);
            jTable_FoodList.getColumnModel().getColumn(13).setMinWidth(40);
            jTable_FoodList.getColumnModel().getColumn(14).setMinWidth(40);
            jTable_FoodList.getColumnModel().getColumn(15).setMinWidth(40);
        }

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel14.setText("Nurituion Facts");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel15.setText("Food Item list");

        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        JButton_Add.setText("Add");
        JButton_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_AddMouseClicked(evt);
            }
        });
        JButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_AddActionPerformed(evt);
            }
        });

        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel16.setText("Filter");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextField_Retailer.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
        jTextField_Retailer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_RetailerActionPerformed(evt);
            }
        });

        jTextField_Meal.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
        jTextField_Meal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MealActionPerformed(evt);
            }
        });

        jTextField_Group.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
        jTextField_Group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_GroupActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Retailer");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setText("Meal");

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel20.setText("Out Dinning");

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel17.setText("Group");

        jLayeredPane1.setLayer(jTextField_Retailer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField_Meal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField_Group, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Meal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jTextField_Group, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jTextField_Retailer, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField_Group, jTextField_Meal});

        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(20, 20, 20)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Retailer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField_Group, jTextField_Retailer});

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Type");

        jComboBox_Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Dinning", "Out Dinning" }));
        jComboBox_Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TypeActionPerformed(evt);
            }
        });

        jRadioButton_Eaten.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jRadioButton_Eaten.setText("Eaten");
        jRadioButton_Eaten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_EatenActionPerformed(evt);
            }
        });

        jTextField_Calendar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextField_Calendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CalendarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Calendar");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Time");

        jTextField_Time.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextField_Time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TimeActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jComboBox_Type, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jRadioButton_Eaten, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextField_Calendar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jTextField_Time, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(47, 47, 47)
                        .addComponent(jComboBox_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton_Eaten))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLayeredPane2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField_Calendar, jTextField_Time});

        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_Eaten))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_Calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("Calories/cal");

        jTextField_Calories.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("Fat / g");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("Portein/ g");

        jTextField_Fat.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jTextField_Portein.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jTextField_Cholesterol.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("Fibre/ g");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setText("Sodium/ g");

        jTextField_Sodium.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setText("Sugar/ g");

        jTextField_Carbohydrate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        jLayeredPane3.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jTextField_Calories, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jTextField_Fat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jTextField_Portein, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jTextField_Cholesterol, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jTextField_Sodium, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jTextField_Carbohydrate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Cholesterol, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_Portein, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_Fat, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_Calories, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_Carbohydrate)
                    .addComponent(jTextField_Sodium, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Calories, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Fat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_Portein, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_Cholesterol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_Sodium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField_Carbohydrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel22.setText("In Dinning");

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel18.setText("Name");

        jTextField_ServingSize.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
        jTextField_ServingSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ServingSizeActionPerformed(evt);
            }
        });

        jComboBox_Unit.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
        jComboBox_Unit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "g", "ml", "cal" ,"unit"}));

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel23.setText("Serving Size");

        jTextField_Name.setText("jTextField1");
        jTextField_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NameActionPerformed(evt);
            }
        });

        jLayeredPane4.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jTextField_ServingSize, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jComboBox_Unit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jTextField_Name, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel18)
                    .addComponent(jLabel23))
                .addGap(14, 14, 14)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(jTextField_ServingSize)
                        .addGap(10, 10, 10)
                        .addComponent(jComboBox_Unit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(jTextField_Name)
                        .addContainerGap())))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_ServingSize, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jComboBox_Unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jLayeredPane5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

         buttonGroup1.add(jRadioButton_Fall);
        jRadioButton_Fall.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jRadioButton_Fall.setText("All");
        jRadioButton_Fall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_FallActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_Featen);
        jRadioButton_Featen.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jRadioButton_Featen.setText("Eaten");
        jRadioButton_Featen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_FeatenActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_Funeaten);
        jRadioButton_Funeaten.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jRadioButton_Funeaten.setText("Uneaten");
        jRadioButton_Funeaten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_FuneatenActionPerformed(evt);
            }
        }); 

        jLayeredPane5.setLayer(jRadioButton_Fall, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jRadioButton_Featen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jRadioButton_Funeaten, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_Funeaten)
                    .addComponent(jRadioButton_Featen)
                    .addComponent(jRadioButton_Fall))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jRadioButton_Fall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_Featen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_Funeaten)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLayeredPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel_FoodItem))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(JButton_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLayeredPane3, jLayeredPane5});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_FoodItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JButton_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLayeredPane5)
                            .addComponent(jLayeredPane3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jRadioButton_FallActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        filter("");
    }                                                 

    private void jRadioButton_EatenActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void jTextField_TimeActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void jTextField_GroupActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void jTextField_MealActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void jTextField_RetailerActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void jRadioButton_FuneatenActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
        filter("false");
    }                                                     

    private void jRadioButton_FeatenActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        filter("true");
    }                                                   

    // update button 
   
    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
       
        int i = jTable_FoodList.getSelectedRow();

        if (i >=0) {
            model.setValueAt(jRadioButton_Eaten.isSelected(),i,0);
            model.setValueAt(jComboBox_Type.getSelectedItem().toString(),i,1);
            model.setValueAt(jTextField_Calendar.getText().toString(),i,2);
            model.setValueAt(jTextField_Time.getText().toString(),i,3);
            model.setValueAt(jTextField_Name.getText().toString(),i,4);
            model.setValueAt(jTextField_ServingSize.getText().toString(),i,5);
            model.setValueAt(jComboBox_Unit.getSelectedItem().toString(),i,6);
            model.setValueAt(jTextField_Retailer.getText().toString(),i,7);
            model.setValueAt(jTextField_Meal.getText().toString(),i,8);
            model.setValueAt(jTextField_Group.getText().toString(),i,9);
            model.setValueAt(jTextField_Calories.getText().toString(),i,10);
            model.setValueAt(jTextField_Fat.getText().toString(),i,11);
            model.setValueAt(jTextField_Portein.getText().toString(),i,12);
            model.setValueAt(jTextField_Cholesterol.getText().toString(),i,13);
            model.setValueAt(jTextField_Sodium.getText().toString(),i,14);
            model.setValueAt(jTextField_Carbohydrate.getText().toString(),i,15);
           
        } else
        {
            JOptionPane.showMessageDialog(this, "Update Error!");
        }
 
        writeTofile();
       
        
    }                                              

    private void JButton_AddActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void JButton_AddMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
          Object [] arr = new Object [] 
            {jRadioButton_Eaten.isSelected(),
            jComboBox_Type.getSelectedItem().toString(),
            jTextField_Calendar.getText(),
            jTextField_Time.getText(),
            jTextField_Name.getText(),
            jTextField_ServingSize.getText(),
            jComboBox_Unit.getSelectedItem().toString(),
            jTextField_Retailer.getText(),
            jTextField_Meal.getText(),
            jTextField_Group.getText(),
            jTextField_Calories.getText(),
            jTextField_Fat.getText(),
            jTextField_Portein.getText(),
            jTextField_Cholesterol.getText(),
            jTextField_Sodium.getText(),
            jTextField_Carbohydrate.getText(),           
        };
        model.insertRow(model.getRowCount(),arr);
        
     writeTofile();
        
        
        
    }                                        

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        int i = jTable_FoodList.getSelectedRow();
        if (i >= 0) {
            model.removeRow(i);
        }
        else {
            JOptionPane.showMessageDialog(this, "Delete Error!");
        }
        writeTofile();
    }                                              
 
    private void jTextField_CalendarActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    // disable/undisable textfield
    private void jComboBox_TypeActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        type_select();
    }                                              

    // talbe clicked,one row chosed. 
    private void jTable_FoodListMouseClicked(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
        int i = jTable_FoodList.getSelectedRow();
        //System.out.println(jTable_FoodList.getValueAt(i,0));
        jRadioButton_Eaten.setSelected((boolean) jTable_FoodList.getValueAt(i,0));
        jComboBox_Type.setSelectedItem((String)jTable_FoodList.getValueAt(i,1));
        jTextField_Calendar.setText((String) jTable_FoodList.getValueAt(i, 2));
        jTextField_Time.setText((String) jTable_FoodList.getValueAt(i, 3));
        jTextField_Name.setText((String) jTable_FoodList.getValueAt(i, 4));
        jTextField_ServingSize.setText((String) jTable_FoodList.getValueAt(i, 5));
        jComboBox_Unit.setSelectedItem((String) jTable_FoodList.getValueAt(i, 6));
        jTextField_Retailer.setText((String) jTable_FoodList.getValueAt(i, 7));
        jTextField_Meal.setText((String) jTable_FoodList.getValueAt(i, 8));
        jTextField_Group.setText((String) jTable_FoodList.getValueAt(i, 9));
        jTextField_Calories.setText((String) jTable_FoodList.getValueAt(i, 10));
        jTextField_Fat.setText((String) jTable_FoodList.getValueAt(i, 11));
        jTextField_Portein.setText((String) jTable_FoodList.getValueAt(i, 12));
        jTextField_Cholesterol.setText((String) jTable_FoodList.getValueAt(i, 13));
        jTextField_Sodium.setText((String) jTable_FoodList.getValueAt(i, 14));
        jTextField_Carbohydrate.setText((String) jTable_FoodList.getValueAt(i, 15));
        
    }                                            

    private void jTable_FoodListAncestorAdded(javax.swing.event.AncestorEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jTextField_ServingSizeActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    private void jTextField_NameActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               
    
      
    
    // Filter data
    private void filter(String query){
         TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model); 
         jTable_FoodList.setRowSorter(tr);
         tr.setRowFilter(RowFilter.regexFilter(query));
    }
    
    
   

    // Variables declaration - do not modify                     
    private javax.swing.JButton JButton_Add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Update;
    javax.swing.JComboBox<String> jComboBox_Type;
    javax.swing.JComboBox<String> jComboBox_Unit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_FoodItem;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    javax.swing.JRadioButton jRadioButton_Eaten;
    private javax.swing.JRadioButton jRadioButton_Fall;
    private javax.swing.JRadioButton jRadioButton_Featen;
    private javax.swing.JRadioButton jRadioButton_Funeaten;
    private javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTable jTable_FoodList;
    javax.swing.JTextField jTextField_Calendar;
    javax.swing.JTextField jTextField_Calories;
    javax.swing.JTextField jTextField_Fat;
    javax.swing.JTextField jTextField_Cholesterol;
    javax.swing.JTextField jTextField_Group;
    javax.swing.JTextField jTextField_Meal;
    javax.swing.JTextField jTextField_Name;
    javax.swing.JTextField jTextField_Portein;
    javax.swing.JTextField jTextField_Retailer;
    javax.swing.JTextField jTextField_ServingSize;
    javax.swing.JTextField jTextField_Sodium;
    javax.swing.JTextField jTextField_Carbohydrate;
    javax.swing.JTextField jTextField_Time;
    // End of variables declaration     
    
    
       public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Calendar getCal() {
		return cal;
	}

	public void setCal(Calendar cal) {
		this.cal = cal;
	}

	public javax.swing.JComboBox<String> getjComboBox_Type() {
		return jComboBox_Type;
	}

	public void setjComboBox_Type(javax.swing.JComboBox<String> jComboBox_Type) {
		this.jComboBox_Type = jComboBox_Type;
	}

	public javax.swing.JComboBox<String> getjComboBox_Unit() {
		return jComboBox_Unit;
	}

	public void setjComboBox_Unit(javax.swing.JComboBox<String> jComboBox_Unit) {
		this.jComboBox_Unit = jComboBox_Unit;
	}

	public javax.swing.JTable getjTable_FoodList() {
		return jTable_FoodList;
	}

	public void setjTable_FoodList(javax.swing.JTable jTable_FoodList) {
		this.jTable_FoodList = jTable_FoodList;
	}

	public javax.swing.JTextField getjTextField_Calendar() {
		return jTextField_Calendar;
	}

	public void setjTextField_Calendar(javax.swing.JTextField jTextField_Calendar) {
		this.jTextField_Calendar = jTextField_Calendar;
	}

	public javax.swing.JTextField getjTextField_Calories() {
		return jTextField_Calories;
	}

	public void setjTextField_Calories(javax.swing.JTextField jTextField_Calories) {
		this.jTextField_Calories = jTextField_Calories;
	}

	public javax.swing.JTextField getjTextField_Fat() {
		return jTextField_Fat;
	}

	public void setjTextField_Fat(javax.swing.JTextField jTextField_Fat) {
		this.jTextField_Fat = jTextField_Fat;
	}

	public javax.swing.JTextField getjTextField_Fibre() {
		return jTextField_Cholesterol;
	}

	public void setjTextField_Fibre(javax.swing.JTextField jTextField_Fibre) {
		this.jTextField_Cholesterol = jTextField_Fibre;
	}

	public javax.swing.JTextField getjTextField_Group() {
		return jTextField_Group;
	}

	public void setjTextField_Group(javax.swing.JTextField jTextField_Group) {
		this.jTextField_Group = jTextField_Group;
	}

	public javax.swing.JTextField getjTextField_Meal() {
		return jTextField_Meal;
	}

	public void setjTextField_Meal(javax.swing.JTextField jTextField_Meal) {
		this.jTextField_Meal = jTextField_Meal;
	}

	public javax.swing.JTextField getjTextField_Name() {
		return jTextField_Name;
	}

	public void setjTextField_Name(javax.swing.JTextField jTextField_Name) {
		this.jTextField_Name = jTextField_Name;
	}

	public javax.swing.JTextField getjTextField_Portein() {
		return jTextField_Portein;
	}

	public void setjTextField_Portein(javax.swing.JTextField jTextField_Portein) {
		this.jTextField_Portein = jTextField_Portein;
	}

	public javax.swing.JTextField getjTextField_Retailer() {
		return jTextField_Retailer;
	}

	public void setjTextField_Retailer(javax.swing.JTextField jTextField_Retailer) {
		this.jTextField_Retailer = jTextField_Retailer;
	}

	public javax.swing.JTextField getjTextField_ServingSize() {
		return jTextField_ServingSize;
	}

	public void setjTextField_ServingSize(javax.swing.JTextField jTextField_ServingSize) {
		this.jTextField_ServingSize = jTextField_ServingSize;
	}

	public javax.swing.JTextField getjTextField_Sodium() {
		return jTextField_Sodium;
	}

	public void setjTextField_Sodium(javax.swing.JTextField jTextField_Sodium) {
		this.jTextField_Sodium = jTextField_Sodium;
	}

	public javax.swing.JTextField getjTextField_Sugar() {
		return jTextField_Carbohydrate;
	}

	public void setjTextField_Carbohydrate(javax.swing.JTextField jTextField_Sugar) {
		this.jTextField_Carbohydrate = jTextField_Sugar;
	}

	public javax.swing.JTextField getjTextField_Time() {
		return jTextField_Time;
	}

	public void setjTextField_Time(javax.swing.JTextField jTextField_Time) {
		this.jTextField_Time = jTextField_Time;
	}
    
    
    
     public void writeTofile(){
         
     String filepath;
                filepath = "/Users/netts/Desktop/D2/FoodItemsToRead.txt";
	        File file = new File(filepath);
	        try{
	         
	            FileWriter fw = new FileWriter(file);
	            BufferedWriter bw = new BufferedWriter(fw);
	        
                    for(int k = 0; k<jTable_FoodList.getRowCount();k++){
	                for(int j=0;j<jTable_FoodList.getColumnCount();j++){
	                bw.write(jTable_FoodList.getValueAt(k,j).toString() +",");   
	                
	                }
	                bw.write("\n");
	            
	            } 
	            
	            bw.close();
	            fw.close();
	        
	        
	        }catch(IOException e) {}
    
    
    
    
}

    @Override
    public void update(FoodItem_Model FoodItem) {
        writeTofile();
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void update(Observable o, Object arg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
     
}
